# Generated by Django 4.2.1 on 2023-06-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=40)),
                ("content", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
